stages:
    - run
    - check

build:
    image: 
      name: hashicorp/terraform 
      entrypoint:
      - /usr/bin/env
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    stage: run
    script:
        - terraform --version
        - cd /builds/root/marketplace/terraform/customers/customer1
        - terraform init 
        - terraform apply -auto-approve 
    artifacts:
        paths:
        - /builds/root/marketplace/terraform/customers/customer1/*.{tfstate}

check:
  stage: check
  image:
    name: alpine/git:latest
    entrypoint:
      - /usr/bin/env 
  script:
    - ls -l 
    - ls -l /builds/root/marketplace/terraform/customers/customer1/
    - cat /builds/root/marketplace/terraform/customers/customer1/*.{tfstate}

