stages:
    - pull
    - check

#build website:
#    image: bitnami/git:2.37.0 
#    stage: pull
#    script:
#        - ls -l /builds/root/marketplace
#    artifacts:
#        paths:
#            - /builds/root/marketplace

build website2:
    image: 
      name: hashicorp/terraform 
      entrypoint:
      - /usr/bin/env
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    stage: check
    script:
        - terraform --version
        - cd /builds/root/marketplace/terraform/customers/customer1
        - terraform init 
