stages:
    - run
    - check





build:
    image: 
      name: hashicorp/terraform 
      entrypoint:
      - /usr/bin/env
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    stage: run
    script:
        - cd ./terraform/customers/customer1
        - terraform init 
        - terraform apply -auto-approve 
    artifacts:
        paths:
        - ./terraform/customers/customer1/*.tfstate
        - ./terraform/customers/customer1/service_node_port

check:
  stage: check
  image:
    name: alpine/git:latest
    entrypoint:
      - /usr/bin/env 
  before_script:
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
  script:
    - git remote set-url origin http://gitlab-ci-token:${ACCESS_TOKEN}@192.168.110.134/root/marketplace.git
    - git add ./terraform/customers/customer1/*.tfstate
    - git commit --allow-empty -m "NodePort:$(cat ./terraform/customers/customer1/service_node_port)"
    - git push origin HEAD:main -o ci.skip

