stages:
    - pull
    - check

build website:
    image: bitnami/git:2.37.0 
    stage: pull
    script:
        - ls -l /builds/root/marketplace

build website2:
    image: hashicorp/terraform 
    stage: check
    script:
        - terraform --version
